REM Build Bat File
REM Precheck the Resource 
"C:\Program Files\MRE_SDK\tools\ResEditor\CmdShell.exe" save  "D:\MyGitHub\mre_auto_screenshot\mre_auto_screenshot.vcproj"
REM Copmile c file 
"C:\Program Files (x86)\CodeSourcery\Sourcery_CodeBench_Lite_for_ARM_EABI\Bin\arm-none-eabi-gcc" -c -fpic -g -mcpu=arm7tdmi-s -fvisibility=hidden -mthumb -mlittle-endian -O2 -D__MRE_COMPILER_GCC__ -fno-exceptions -fno-non-call-exceptions -o "D:\MyGitHub\mre_auto_screenshot\arm\gccmain.o" -c "C:\Program Files\MRE_SDK\lib\MRE30\src\gccmain.c"      -D _MINIGUI_LIB_ -D _USE_MINIGUIENTRY -D _NOUNIX_ -D _FOR_WNC -D __MRE_SDK__ -D   __MRE_VENUS_NORMAL__  -D  __MMI_MAINLCD_240X320__ -I "C:\Program Files\MRE_SDK\include" -I "C:\Program Files\MRE_SDK\include\service" -I "C:\Program Files\MRE_SDK\include" -I "C:\Program Files\MRE_SDK\include\service" -I "D:\MyGitHub\mre_auto_screenshot\include" -I "D:\MyGitHub\mre_auto_screenshot\include\service" -I "D:\MyGitHub\mre_auto_screenshot\include\component" -I "D:\MyGitHub\mre_auto_screenshot\ResID" -I "D:\MyGitHub\mre_auto_screenshot\src\app\widget" -I "D:\MyGitHub\mre_auto_screenshot\src\app\launcher" -I "D:\MyGitHub\mre_auto_screenshot\src\app\wallpaper" -I "D:\MyGitHub\mre_auto_screenshot\src\app\screen_lock" -I "D:\MyGitHub\mre_auto_screenshot\include\service" -I "D:\MyGitHub\mre_auto_screenshot\include\component" -I "D:\MyGitHub\mre_auto_screenshot\include\service" -I "D:\MyGitHub\mre_auto_screenshot\src\framework" -I "D:\MyGitHub\mre_auto_screenshot\src\framework\ui_core\base" -I "D:\MyGitHub\mre_auto_screenshot\src\framework\ui_core\mvc" -I "D:\MyGitHub\mre_auto_screenshot\src\framework\ui_core\pme" -I "D:\MyGitHub\mre_auto_screenshot\src\framework\mmi_core" -I "D:\MyGitHub\mre_auto_screenshot\src\ui_engine\vrt\interface" -I "D:\MyGitHub\mre_auto_screenshot\src\component" -I "D:\MyGitHub\mre_auto_screenshot\src\ui_engine\framework\xml" -I "D:\MyGitHub\mre_auto_screenshot"
REM Copmile c file 
"C:\Program Files (x86)\CodeSourcery\Sourcery_CodeBench_Lite_for_ARM_EABI\Bin\arm-none-eabi-gcc" -c -fpic -g -mcpu=arm7tdmi-s -fvisibility=hidden -mthumb -mlittle-endian -O2 -D__MRE_COMPILER_GCC__ -fno-exceptions -fno-non-call-exceptions -o "D:\MyGitHub\mre_auto_screenshot\arm\mre_auto_screenshot.o" -c "d:\MyGitHub\mre_auto_screenshot\mre_auto_screenshot.c"      -D _MINIGUI_LIB_ -D _USE_MINIGUIENTRY -D _NOUNIX_ -D _FOR_WNC -D __MRE_SDK__ -D   __MRE_VENUS_NORMAL__  -D  __MMI_MAINLCD_240X320__ -I "C:\Program Files\MRE_SDK\include" -I "C:\Program Files\MRE_SDK\include\service" -I "C:\Program Files\MRE_SDK\include" -I "C:\Program Files\MRE_SDK\include\service" -I "D:\MyGitHub\mre_auto_screenshot\include" -I "D:\MyGitHub\mre_auto_screenshot\include\service" -I "D:\MyGitHub\mre_auto_screenshot\include\component" -I "D:\MyGitHub\mre_auto_screenshot\ResID" -I "D:\MyGitHub\mre_auto_screenshot\src\app\widget" -I "D:\MyGitHub\mre_auto_screenshot\src\app\launcher" -I "D:\MyGitHub\mre_auto_screenshot\src\app\wallpaper" -I "D:\MyGitHub\mre_auto_screenshot\src\app\screen_lock" -I "D:\MyGitHub\mre_auto_screenshot\include\service" -I "D:\MyGitHub\mre_auto_screenshot\include\component" -I "D:\MyGitHub\mre_auto_screenshot\include\service" -I "D:\MyGitHub\mre_auto_screenshot\src\framework" -I "D:\MyGitHub\mre_auto_screenshot\src\framework\ui_core\base" -I "D:\MyGitHub\mre_auto_screenshot\src\framework\ui_core\mvc" -I "D:\MyGitHub\mre_auto_screenshot\src\framework\ui_core\pme" -I "D:\MyGitHub\mre_auto_screenshot\src\framework\mmi_core" -I "D:\MyGitHub\mre_auto_screenshot\src\ui_engine\vrt\interface" -I "D:\MyGitHub\mre_auto_screenshot\src\component" -I "D:\MyGitHub\mre_auto_screenshot\src\ui_engine\framework\xml" -I "D:\MyGitHub\mre_auto_screenshot"
REM Link app 
"C:\Program Files (x86)\CodeSourcery\Sourcery_CodeBench_Lite_for_ARM_EABI\Bin\arm-none-eabi-gcc" -o "D:\MyGitHub\mre_auto_screenshot\mre_auto_screenshot.axf"  "D:\MyGitHub\mre_auto_screenshot\arm\gccmain.o"  "D:\MyGitHub\mre_auto_screenshot\arm\mre_auto_screenshot.o" -fpic -msvr4-struct-return -pie  -T "C:\Program Files\MRE_SDK\lib\MRE30\armgcc_t\scat.ld" -l:"C:\Program Files\MRE_SDK\lib\MRE30\armgcc_t\percommon.a" -l:"C:\Program Files\MRE_SDK\lib\MRE30\armgcc_t\peraudio.a" -l:"C:\Program Files\MRE_SDK\lib\MRE30\armgcc_t\perfile.a" -l:"C:\Program Files\MRE_SDK\lib\MRE30\armgcc_t\perpro.a" -l:"C:\Program Files\MRE_SDK\lib\MRE30\armgcc_t\persysstorage.a" -l:"C:\Program Files\MRE_SDK\lib\MRE30\armgcc_t\persysfile.a"
REM Pack resource to app 
"C:\Program Files\MRE_SDK\tools\ResEditor\CmdShell.exe" pack -silent -resolution 240x320 -o "D:\MyGitHub\mre_auto_screenshot\mre_auto_screenshot.pkd" -e AXF "D:\MyGitHub\mre_auto_screenshot\mre_auto_screenshot.vcproj" "D:\MyGitHub\mre_auto_screenshot\mre_auto_screenshot.axf"
REM Add tag infromation 
"C:\Program Files\MRE_SDK\tools\PackDigist.exe" "D:\MyGitHub\mre_auto_screenshot\mre_auto_screenshot.vcproj" "mre_auto_screenshot" "0.1.0" "RDZDX" "0" "supportBg" "Not Support rotate" "mre_auto_screenshot" "mre_auto_screenshot" "mre_auto_screenshot" "9123456789123456" "content" " Audio File ProMng SysStorage SysFile" "vxp" "GCC" "PKD" "UnCompress" "NoVPI" "UnAdaptable" "15728960" "UnSysMemAble" "
    " "-1" "UNPUSH" "-1" ""  "UnAutoStart"  "UnTransferImg" "NoIdleShortcut"  D:\MyGitHub\mre_auto_screenshot\arm D:\MyGitHub\mre_auto_screenshot\build.log

